export * from "./clamp";
export * from "./lerp";
export * from "./mat";
export * from "./max";
export * from "./min";
export * from "./mult";
export * from "./splat";
export * from "./tex2D-grad";
export * from "./vec";
